name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ env.BUILD_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Generate Build ID
        id: build_id
        run: echo "BUILD_ID=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Build project
        run: pnpm build
        env:
          NEXT_PUBLIC_BASE_PATH: /react-gh-pages
          BUILD_ID: ${{ env.BUILD_ID }}

      - name: Create release artifact
        run: |
          cd out
          zip -r ../release.zip ./*
          cd ..
          mkdir -p release-artifact
          mv release.zip release-artifact/

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release-artifact/release.zip
          retention-days: 1

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: generate_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            AUTO_TAG="v0.0.0-${SHORT_SHA}"
            echo "VERSION=${AUTO_TAG}" >> $GITHUB_OUTPUT
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag $AUTO_TAG
            git push origin $AUTO_TAG
          fi

      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_version.outputs.VERSION }}
          files: release.zip
          name: Release ${{ steps.generate_version.outputs.VERSION }}
          body: |
            Release ${{ steps.generate_version.outputs.VERSION }}
            Build ID: ${{ needs.build-and-deploy.outputs.build_id }}
            Deployment URL: https://nayakmk.github.io/react-gh-pages
            
            ## What's Changed
            ${{ steps.generate_version.outputs.IS_TAG == 'true' && '* Manual release' || '* Auto-generated release from commit' }}
            * Build timestamp: ${{ needs.build-and-deploy.outputs.build_id }}
            * Commit: ${{ github.sha }}
            * Includes full static export of the Next.js application
          draft: false
          prerelease: ${{ steps.generate_version.outputs.IS_TAG != 'true' }}
          token: ${{ secrets.GITHUB_TOKEN }}